DOCUMENTATION: Transalate First Paragraph From The Theory
hassanhabib/The-Standard-Uzbek pull request #18
Opened 2022-08-28 17:40 UTC by mrakhmadjon

2022-08-28 17:42 UTC, Xakimov1610 approved these changes

2022-09-02 13:16 UTC, ElbekDeveloper requested changes

2022-09-02 13:16 UTC, ElbekDeveloper commented on 0. Kirish/0.0 Nazariya.md
> +Har qanday tizimni loyihalashda dizaynerlar o’zlarining dizaynini ma'lum bir nazariya bilan qo'llab-quvvatlashlari kerak. Nazariyalar - dizayn maqsadlari, modellari va simulyatsiyalarining ma'lum bir
`... loyihalashda, yetakchilar o'zlarining qarorlarini ma'lum bir...` designer bu yerda ko'proq qaror qabul qila oladigan, dasturning arxitekturasini chizadigan odamlar nazarda tutilyapti. `Yetakchi` manimcha yaxshi tarjima bo'ladi.

2022-09-02 13:16 UTC, ElbekDeveloper commented on 0. Kirish/0.0 Nazariya.md
> +Har qanday tizimni loyihalashda dizaynerlar o’zlarining dizaynini ma'lum bir nazariya bilan qo'llab-quvvatlashlari kerak. Nazariyalar - dizayn maqsadlari, modellari va simulyatsiyalarining ma'lum bir
`...ahamiyatga ega .` nuqatadan oldin ortiqcha probelni olib tashlang, iltimos.

2022-09-02 13:16 UTC, ElbekDeveloper commented on 0. Kirish/0.0 Nazariya.md
> +Bu qanchalik Chalkash tuyulmasin, har qanday tizim dizayner tomonidan yaratilgan yoki oldingi dizaynerlarning usullaridan meros bo'lib qolgan kamida bitta nazariyaning ta'siriga uchraydi. Ta'sir qilu
`Bu qanchalik Chalkash...` => `chalkash` kichkina harfga o'zgartiring.

2022-09-02 13:16 UTC, ElbekDeveloper commented on 0. Kirish/0.0 Nazariya.md
> +Koinot haqidagi nazariyani - omon qolish, evolyutsiya va zavqlanish hissi haqidagi har xil ertaklar bilan boyitib, hayotdagi maqsadni yanada aniqlashtirishi mumkin.
`ertaklar` => `hikoyalar`

2022-09-06 05:15 UTC, ElbekDeveloper approved these changes

2022-09-06 05:15 UTC, merged