Update 1. Kirish.md
hassanhabib/The-Standard-Uzbek pull request #2
Opened 2022-08-22 13:15 UTC by Muhammad-Diyor

Bir paragraf qo'shildi, joriy paragraflardagi kichik xatoliklar to'g'rilandi.

2022-08-22 20:55 UTC, Xakimov1610 commented
**Men deb yozilishi tarafdoriman** 👍

2022-08-22 21:26 UTC, Xakimov1610 reviewed
**Takliflar**

1. **yig'gan**  _so'zini_ => **to'plagan** , **jamlagan** _so'zlariga almashtirsak_ .
2. **o'zida jo etgan**  _jumlasini_ => **o'zida mujassam etgan** _jumlasiga almashirsak_ .

2022-08-23 07:27 UTC, ElbekDeveloper requested changes

2022-08-23 07:27 UTC, ElbekDeveloper commented on 0. Kirish/0. Kirish.md
> +Bu - Me'yor. Dasturlash sohasidagi ko'p yillik tajribaning jamlanmasi. Men buni sizga ilmning keng ummonida o'z yo'lingizni topishingizga yordam berish uchun yozdim. Me'yor mukammal emas va hech qach
Oxirgi gap tushunarsiz bo'lib qolgandek. Shuni yana bir o'ylab ko'ra olasizmi, iltimos?

2022-08-23 07:27 UTC, ElbekDeveloper commented on 0. Kirish/0. Kirish.md
> +Me'yor - umumdunyo muxandislariga murojaatdir. Uni o'qib chiqishsin va dasturiy ta'minot sanoatiga munosib Me'yorni o'z bilim va tajribalari bilan boyitishsin. Bugungi kunda, Yer, insoniyat va barcha
`umumdunyo` so'zini `butun jahon` so'ziga almashtirsak nima deysiz?

2022-08-23 07:27 UTC, ElbekDeveloper commented on 0. Kirish/0. Kirish.md
> +Me'yor - umumdunyo muxandislariga murojaatdir. Uni o'qib chiqishsin va dasturiy ta'minot sanoatiga munosib Me'yorni o'z bilim va tajribalari bilan boyitishsin. Bugungi kunda, Yer, insoniyat va barcha
`Kodlar` bo'lmaydi `Kod ummoni`

2022-08-23 07:27 UTC, ElbekDeveloper commented on 0. Kirish/0. Kirish.md
> +Me'yor - umumdunyo muxandislariga murojaatdir. Uni o'qib chiqishsin va dasturiy ta'minot sanoatiga munosib Me'yorni o'z bilim va tajribalari bilan boyitishsin. Bugungi kunda, Yer, insoniyat va barcha
`accord` so'zini ham `qadrlash` deb tarjimasini ko'rish kerak...

2022-08-23 07:28 UTC, ElbekDeveloper commented
https://www.youtube.com/watch?v=DdoeLhTogNk mana shu video ko'rsatilganidek yangi pull request ochib. Me'yoriy commit history qilib bera olasizmi?
@Muhammad-Diyor

2022-08-23 23:06 UTC, closed without merging