DOCUMENTATION: 2 more files translated and added
hassanhabib/The-Standard-Uzbek pull request #7
Opened 2022-08-24 15:32 UTC by Muhammad-Diyor

2022-08-24 18:51 UTC, Xakimov1610 requested changes

2022-08-24 18:51 UTC, Xakimov1610 commented on 0. Kirish/0. Kirish.md
> +Men me'yorlarni yig'dim. Va u ko'p chalkashliklarni bartaraf qilishi va muhandislarga eng muhim narsaga e'tibor qaratishiga, ya'ni, texnologiyani yuqori maqsadlar uchun vosita sifatida ishlatishlarig
- [ ] 1. **Men me'yorlarni yig'dim.**  => `Men ushbu Me'yorda ko'plab M'yoorlarni jamladim, so‘ng mualliflik qildim.` _desak bo'ladimi ?_

- [ ] 2. `Umid qilamanki, bu ko'p chalkashliklarni bartaraf qiladi va muhandislarga eng muhim masalalarga e'tibor qaratish imkonini beradi - texnologiyadan yuqori maqsadlar yo'lida foydalanish va unga teng qiymatli maqsadlarni belgilashga ko'maklashadi.`

- [ ] 3. **Va biz yoshlarga u haqida qanday ta'lim berishimiz muhim.**  => `Va biz yoshlarga bu borada qanday ta'lim berishimiz muhim.`

> Comment qoldiringlar fikringiz men uchun qiziq . 🤩

2022-08-24 18:51 UTC, Xakimov1610 commented on 0. Kirish/0. Kirish.md
> +Mohiyatan, Me'yor - chinakam mustahkam tizimlarga erishishimiz uchun dizayn va ishlanmalarimizni boyitishda davom etuvchi SOLID tamoyillari va boshqa ko'plab amaliyot va namunalarning men tomonimdan
`oyga qo'nadigan `o'rniniga =>` oyga qo'nishday` desak yahshiroq bo'larmidi ?

2022-08-24 19:45 UTC, Muhammad-Diyor commented on 0. Kirish/0. Kirish.md
> +Mohiyatan, Me'yor - chinakam mustahkam tizimlarga erishishimiz uchun dizayn va ishlanmalarimizni boyitishda davom etuvchi SOLID tamoyillari va boshqa ko'plab amaliyot va namunalarning men tomonimdan
Menimcha yo'q. Oyga qo'nadigan mustahkam tizimlar deyilyabdi.

2022-08-24 19:53 UTC, Muhammad-Diyor commented on 0. Kirish/0. Kirish.md
> +Men me'yorlarni yig'dim. Va u ko'p chalkashliklarni bartaraf qilishi va muhandislarga eng muhim narsaga e'tibor qaratishiga, ya'ni, texnologiyani yuqori maqsadlar uchun vosita sifatida ishlatishlarig
1..2 Ma'qul, o'zgartirdim.

3. Taklifingizga ko'ra o'zgartirildi.

2022-08-25 03:34 UTC, ElbekDeveloper requested changes

2022-08-25 03:34 UTC, ElbekDeveloper commented on 0. Kirish/0. Kirish.md
>  Ushbu Me'yor butun dunyo bo'ylab muhandislar uchun murojaatdir: Uni o'qib chiqing va dasturiy ta'minot sanoatiga munosib Me'yorni o'z bilim va tajribalaringiz bilan boyiting. Biz bugungi kunda, Yer,
`Uni o'qib chiqing va dasturiy ta'minot sanoatiga munosib Me'yorni o'z bilim va tajribalaringiz bilan boyiting.` mana shu gap asl kitobdagi ma'noni aks ettirmayapti nazarimda. Tarjima qilishga harakat qildim: 
`uni o'qib chiqing va muhandislik sohasiga mos keluvchi muhandislik Me'yorini boyitish uchun ularning tajriba va bilimlaridan bahramand bo'ling`

2022-08-25 03:37 UTC, merged