DOCUMENTATION: Translate 2 Paragraphs From Brokers
hassanhabib/The-Standard-Uzbek pull request #75
Opened 2023-01-01 06:53 UTC by iamDiyorjon

2023-01-03 05:08 UTC, ElbekDeveloper requested changes

2023-01-03 05:08 UTC, ElbekDeveloper commented on 1. Brokerlar/Brokerlar.md
> +### 1.2.1 Oqim Nazorati Yo'q
Mantiq Nazorati Mumkin Emas

2023-01-03 05:08 UTC, ElbekDeveloper commented on 1. Brokerlar/Brokerlar.md
> +Brokerlar oqimni boshqarishning (if-shart opearatori, while-sikl yoki switch case -tanlash operatori kabi) hech qanday shakliga ega bermasligi kerak ,chunki oqimni boshqarish biznes mantiq hisoblanad
oqim boshqaruvidan ko'ra, mantiq nazorati chiroyli chiqadi manimcha

2023-01-03 05:08 UTC, ElbekDeveloper commented on 1. Brokerlar/Brokerlar.md
> +Brokerlar oqimni boshqarishning (if-shart opearatori, while-sikl yoki switch case -tanlash operatori kabi) hech qanday shakliga ega bermasligi kerak ,chunki oqimni boshqarish biznes mantiq hisoblanad
ega bermasligi emas ega bo'lmasligi kerak

2023-01-03 05:08 UTC, ElbekDeveloper commented on 1. Brokerlar/Brokerlar.md
> +Brokerlar oqimni boshqarishning (if-shart opearatori, while-sikl yoki switch case -tanlash operatori kabi) hech qanday shakliga ega bermasligi kerak ,chunki oqimni boshqarish biznes mantiq hisoblanad
biznes mantiq hisoblanadi o'rniga biznes g'oyasi yaxshiroq

2023-01-03 05:08 UTC, ElbekDeveloper commented on 1. Brokerlar/Brokerlar.md
> +Xatoliklarga ishlov berish ham oqimni boshqarishning bir shakli. Brokerlar-hech qanday xatoliklarga ishlov bermasligi kerak, aksincha ularning brokerlarga qo'shni bo'lgan xizmatlar qatlamiga o'tishig
oqim boshqarish => mantiq nazorati

2023-01-03 05:08 UTC, ElbekDeveloper commented on 1. Brokerlar/Brokerlar.md
> +Xatoliklarga ishlov berish ham oqimni boshqarishning bir shakli. Brokerlar-hech qanday xatoliklarga ishlov bermasligi kerak, aksincha ularning brokerlarga qo'shni bo'lgan xizmatlar qatlamiga o'tishig
xaritalash o'rniga tuslash degan so'z ishlatish kerak, yoki moslashtirish qaysi yoqsa birini tanglang

2023-01-25 07:41 UTC, ElbekDeveloper commented on 1. Brokerlar/Brokerlar.md
> +### 1.2.3 Konfiguratsiyalariga egalik qilish
Sozlamalarga Egalik Qilish 
yoki
O'z-o'zini Sozlay Olish

2023-01-25 07:41 UTC, ElbekDeveloper commented on 1. Brokerlar/Brokerlar.md
> +### 1.2.4 MahalliyTurlar
Mahalliy Turlar

2023-01-25 07:41 UTC, ElbekDeveloper commented on 1. Brokerlar/Brokerlar.md
> +Brokerlar  xizmatlar(brokerlarga qo'shni)qatlami tomonidan o'tgan primitive turlar(int,string,char) asosida tashqi model ob'ektini qurishlari mumkin.
primitive -> sodda

2023-01-25 07:41 UTC, ElbekDeveloper commented on 1. Brokerlar/Brokerlar.md
> +Brokerlar  xizmatlar(brokerlarga qo'shni)qatlami tomonidan o'tgan primitive turlar(int,string,char) asosida tashqi model ob'ektini qurishlari mumkin.
ob'ekt -> obyekt

2023-01-25 07:41 UTC, ElbekDeveloper commented on 1. Brokerlar/Brokerlar.md
> +Misol uchun, elektron pochta xabarnomasi brokeridagi  `.Send(...)` funksiyasi  subject, content yoki address kabi asosiy kiritish parametrlarini talab qilishi quyidagicha bo'ladi.
so'zlarni tarjima qiling

2023-01-26 16:05 UTC, iamDiyorjon commented
![image](https://user-images.githubusercontent.com/113177785/214886431-0182a78c-45e4-4ab8-891a-c9092d01b378.png)

need help translating this part

2023-03-15 14:59 UTC, abbosbeck reviewed
Spelling mistakes

2023-03-15 14:59 UTC, abbosbeck commented on 1. Brokerlar/Brokerlar.md
> +Misol uchun, ma'lumotlar bazasidan talabalar ro'yhatini oladigan broker metodi quyidagicha ko'rinishga ega:
*ro'yxatini

2023-03-15 14:59 UTC, abbosbeck commented on 1. Brokerlar/Brokerlar.md
> +Brokerlar uchun tuzilgan shartnomalar, uning barcha vazifalarini ko'rsatishi uchun imkon qadar generic (umumiy) bo'lishi kerak; masalan, ma'lum bir texnologiya yoki infratuzilmani ko'rsatish uchun `I
123-qator eng oxirigi so'zi *foydalanamiz

2023-03-15 14:59 UTC, abbosbeck commented on 1. Brokerlar/Brokerlar.md
> +Yagona ombor brokeri orqali shartnoma nomi bilan bir xil nomni saqlab qolish qulayroq.Ammo brokerlarni implementatsiya (dasturga kiritganimizda) qilganimizda, bularning barchasi shunga o'xshash vazif
*miqdoriga bog'liq bo'ladi

2023-03-15 14:59 UTC, abbosbeck commented on 1. Brokerlar/Brokerlar.md
> +Broker bilan qo'shni service(xizmat) qavati faqat entity brokerlarini chaqirishi  mumkin, chunki ular logikani davom etishdan oldin qabul qilgan yoki taqdim etgan ma'lumotlarni bir neshta tekshirishd
oxiridan 3-so'z: *o'tkazishni

2023-03-15 14:59 UTC, abbosbeck commented on 1. Brokerlar/Brokerlar.md
> +Vaqt o'tishi bilan men faoliyatim davomida ishlagan muhandislardan ba'zi umumiy savollar paydo bo'ldi. Ushbu savollarning ba'zilari bir necha marta takrorlanganligi sababli, men brokerlarning boshqa
ttaqdim -> taqdim

2023-03-15 14:59 UTC, abbosbeck commented on 1. Brokerlar/Brokerlar.md
> +Ammo SOLID aniq ko'rsatmalar emas, balki printsiplar bo'lganligi sababli, ushbu printsipga erishish uchun barcha turli xil implementatsiyalar va patternlarni nazarda tutiladi.
printsiplar -> prinsiplar

2023-03-24 09:07 UTC, merged