DOCUMENTATION: Translate Testimonials
hassanhabib/The-Standard-Uzbek pull request #84
Opened 2023-03-03 19:28 UTC by OlimSadullaev

Closes #83

2023-03-04 07:34 UTC, ElbekDeveloper requested changes

2023-03-04 07:34 UTC, ElbekDeveloper commented on 0. Kirish/0.3 Guvohliklar.md
> +"Me'yor xavotirni uzoqlashtirishga yordam beradi. Turlixil jamoalar o'rtasidagi loyiha qoliblarini birlashtirishga yordam beradi."
Turlixil => Turli xil

2023-03-04 07:34 UTC, ElbekDeveloper commented on 0. Kirish/0.3 Guvohliklar.md
> +Katta dasturiy ta'minot muhandisi
Katta dasturiy ta'minot muhandisi => Katta Dasturiy Ta'minot Muhandisi

2023-03-04 07:34 UTC, ElbekDeveloper commented on 0. Kirish/0.3 Guvohliklar.md
> +Katta raqamli Dasturchi
Katta raqamli Dasturchi => Katta Raqamli Dasturchi

2023-03-04 07:34 UTC, ElbekDeveloper commented on 0. Kirish/0.3 Guvohliklar.md
> +"Me'yor xavotirni uzoqlashtirishga yordam beradi. Turlixil jamoalar o'rtasidagi loyiha qoliblarini birlashtirishga yordam beradi."
Me'yor xavotirni uzoqlashtirishga yordam beradi => Me'yor loyiha maqsadlarini bir-biridan ajratishga yordam beradi.

2023-03-04 07:34 UTC, ElbekDeveloper commented on 0. Kirish/0.3 Guvohliklar.md
> +"Me'yor Dasturlarni ishlab chiqish tezligini oshirishga yordam berdi."
Dasturlarni => dasturlarni

2023-03-04 07:34 UTC, ElbekDeveloper commented on 0. Kirish/0.3 Guvohliklar.md
> +Dasturchi muhandis
M katta bilan

2023-03-04 07:34 UTC, ElbekDeveloper commented on 0. Kirish/0.3 Guvohliklar.md
> +"Yaxshiroq ichki va jamoaviy hamkorlik. Kamroq meetinglar va bo'shvaqtlarni samarali sarflash. Birqancha umumiy tushunchalar bundan tashqari aloqa va hamkorlikni rivojlantiradigan so'zlar."
meetinglar => uchrashuvlar

2023-03-04 07:34 UTC, ElbekDeveloper commented on 0. Kirish/0.3 Guvohliklar.md
> +"Yaxshiroq ichki va jamoaviy hamkorlik. Kamroq meetinglar va bo'shvaqtlarni samarali sarflash. Birqancha umumiy tushunchalar bundan tashqari aloqa va hamkorlikni rivojlantiradigan so'zlar."
bo'shvaqtlarni samarali sarflash => "tab"mi yoki "bo'sh katakmi" kabi muammoli vaziyatga kech qoyadi va bunday uchrashuvlarni kamaytiradi.

2023-03-04 07:34 UTC, ElbekDeveloper commented on 0. Kirish/0.3 Guvohliklar.md
> +"Yaxshiroq ichki va jamoaviy hamkorlik. Kamroq meetinglar va bo'shvaqtlarni samarali sarflash. Birqancha umumiy tushunchalar bundan tashqari aloqa va hamkorlikni rivojlantiradigan so'zlar."
PRs, continuous integration/feedback and engineering quality become automatic. Easily one of the best ways to remove the roadblocks that inhibit new teams." qolgan

2023-03-04 07:34 UTC, ElbekDeveloper commented on 0. Kirish/0.3 Guvohliklar.md
> +"Mening o'ylashimcha Me'yor harbir dasturchining mehnat quroli bo'lishi lozim. Bu ba'zi taxminlardan uzoqlashtiradi. Har bir dasturchining no'malum va shubhali jim turishi keyinchalik savolarning jav
harbir => har bir

2023-03-04 07:34 UTC, ElbekDeveloper commented on 0. Kirish/0.3 Guvohliklar.md
> +"Muhandislarning o'sishi uchun asos yaratildi. Dasturchi muhandislarni kodlarni desinlash va arxitekturalashga yordam berdi, dastur tomonidan foydalaniladigan resurslar chizmalarni o'z ichiga oladi.
desinlash? => loyihalash

2023-03-04 07:34 UTC, ElbekDeveloper commented on 0. Kirish/0.3 Guvohliklar.md
> +"Deyarli 15 yillik dasturiy ta'minot muhandisi bo'la turib unitark etgandim va qayta boshladim, Standart menga kodlash va dasturiy ta'minot dizayni bo'yicha ishonch va ko'nikmalarni tezda tiklashga y
Standart => Me'yor

2023-03-04 07:34 UTC, ElbekDeveloper commented on 0. Kirish/0.3 Guvohliklar.md
> +"Me'yor menga umid berdi, bilimlarimni oshirdi va yuqori daromadli dasturlar yaratishimga imkon berdi. Agar bu "yaxshi" dasturiy ta'minotni qanday yozish bo'yicha keyingi texnik kitob deb o'ylasangiz
Me'yor menga dasturiy ta'minot muhandisligini o'rgatdi => Me'yor menga `nafaqat` dasturiy ta'minot muhandisligini o'rgatdi

2023-03-04 07:34 UTC, ElbekDeveloper commented on 0. Kirish/0.3 Guvohliklar.md
> +Full Stack Developr
Full Stack Dasturchi

2023-03-04 07:34 UTC, ElbekDeveloper commented on 0. Kirish/0.3 Guvohliklar.md
> +
bular kerak emas

2023-03-09 15:38 UTC, Javlonbek-dev commented on 0. Kirish/0.3 Guvohliklar.md
> +"Me'yor oson dizaynlashda yordam berdi, kod asoslarini o'sh tez va samarali, vazifalarni rejalashtirish yengil"
kod asoslarini o'sh tez => kod asoslarini o'qish tez

2023-03-09 15:38 UTC, Javlonbek-dev commented on 0. Kirish/0.3 Guvohliklar.md
> +"Yaxshiroq ichki va jamoaviy hamkorlik. Kamroq uchrashuvlar va "tab"mi yoki "bo'sh katakmi" kabi muammoli vaziyatga kech qoyadi va bunday uchrashuvlarni kamaytiradi. Birqancha umumiy tushunchalar bun
kech => chek

2023-03-09 15:38 UTC, Javlonbek-dev commented on 0. Kirish/0.3 Guvohliklar.md
> +"Me'yor kod bilan bo'g'liq bo'lgan noaniqliklarni bartaraf etdi. Spetsifikatsiya va tavsif tili(SDL)da asosan ko'rinmaydigan holatlarni va muammolarni o'z ichiga oladi. Me'yorni ishlatadigan harqanda
harqanday dasturchiga turlixildagi  => har qanday dasturchiga turli xildagi

2023-03-09 15:38 UTC, Javlonbek-dev commented on 0. Kirish/0.3 Guvohliklar.md
> +"Mening o'ylashimcha Me'yor har bir dasturchining mehnat quroli bo'lishi lozim. Bu ba'zi taxminlardan uzoqlashtiradi. Har bir dasturchining no'malum va shubhali jim turishi keyinchalik savolarning ja
harqanday kampaniyalaruchun => har qanday kampaniyalar uchun

2023-03-09 15:38 UTC, Javlonbek-dev commented on 0. Kirish/0.3 Guvohliklar.md
> +"Me'yor menga qo'rquvni bosishimga yordam berdi, chunki men maqsadlarimni amalga oshirish uchun yetarlicha kuchli tizim yaratishga harakat qildim. Mahsulot va foydalanuvchi interfeysini yaratish oson
Hasanning rejasi men eng yaxshi=> Hasanning rejasi meni eng yaxshi

2023-03-09 15:38 UTC, Javlonbek-dev commented on 0. Kirish/0.3 Guvohliklar.md
> +"Deyarli 15 yillik dasturiy ta'minot muhandisi bo'la turib unitark etgandim va qayta boshladim, Me'yor menga kodlash va dasturiy ta'minot dizayni bo'yicha ishonch va ko'nikmalarni tezda tiklashga yor
unitark=> uni tark

2023-03-15 12:01 UTC, ElbekDeveloper approved these changes

2023-03-15 12:01 UTC, merged