DOCUMENTATION: Translate The First Part of Unit
hassanhabib/The-Standard-Uzbek pull request #94
Opened 2023-03-29 10:41 UTC by dostonbek-andijonlik

Closes #91

2023-04-09 08:51 UTC, ElbekDeveloper requested changes

2023-04-09 08:51 UTC, ElbekDeveloper commented on 2. Xizmatlar/2.3 Orchestrations/2.3 Orchestraions.md
> +Orkestratsiya servislari murakkab logika amallarini bajarish uchun ko'plab fundament va ishlanayotgan servislar orasidagi kombinatorlardir. Ularning asosiy majburiyatlari ko'p obyektli mantiqiy opera
ishlanayotgan servislar => ishlov berish servicelari
fundament servislar => asos servislar

2023-04-09 08:51 UTC, ElbekDeveloper commented on 2. Xizmatlar/2.3 Orchestrations/2.3 Orchestraions.md
> +Orkestratsiya servislari murakkab logika amallarini bajarish uchun ko'plab fundament va ishlanayotgan servislar orasidagi kombinatorlardir. Ularning asosiy majburiyatlari ko'p obyektli mantiqiy opera
poydevor => asos

2023-04-09 08:51 UTC, ElbekDeveloper commented on 2. Xizmatlar/2.3 Orchestrations/2.3 Orchestraions.md
> +Orkestr servislarining asosiy mas'uliyati ikki yoki uchta biznes subektini talab qiladigan operatsiyalarni qamrab olishdir.
Orkestr => Orkestratsiya

2023-04-09 08:51 UTC, ElbekDeveloper commented on 2. Xizmatlar/2.3 Orchestrations/2.3 Orchestraions.md
> +Orkestr servislarining asosiy mas'uliyati ikki yoki uchta biznes subektini talab qiladigan operatsiyalarni qamrab olishdir.
subektini => biznes g'oyani birlashtirishni talab...

2023-04-09 08:51 UTC, ElbekDeveloper commented on 2. Xizmatlar/2.3 Orchestrations/2.3 Orchestraions.md
> +Yuqoridagi misolda <mark>LibraryCardOrchestrationService</mark> murakkab operatsiyani bajarish uchun <mark>StudentProcessingService</mark>  va <mark>LibraryCardProcessingService</mark>  ni ham chaqir
100% markdown tilida yozing. html qo'shmang

2023-04-09 08:51 UTC, ElbekDeveloper commented on 2. Xizmatlar/2.3 Orchestrations/2.3 Orchestraions.md
> +Berilgan talaba uchun kutubxona kartasini yaratish operatsiyasini shunchaki kutubxona kartasi xizmatiga qo'ng'iroq qilish orqali amalga oshirish mumkin emas; chunki kutubxona kartasi xizmati (qayta i
qo'ng'iroq => chaqirish

2023-04-09 08:51 UTC, ElbekDeveloper commented on 2. Xizmatlar/2.3 Orchestrations/2.3 Orchestraions.md
> +Shuni tushunish muhimki, orkestratsiya servislari faqat ibtidoiy yoki yuqori tartibli bo'lishi mumkin bo'lgan ko'p obektli operatsiyalarni birlashtirish kerak bo'lganda talab qilinadi. Ba'zi arxitekt
Shuni tushunish muhimki, orkestratsiya servislari faqat ibtidoiy yoki yuqori tartibli bo'lishi mumkin bo'lgan ko'p obektli operatsiyalarni birlashtirish kerak bo'lganda talab qilinadi.

bu gapni yanada soddaroq qiling

2023-04-09 08:51 UTC, ElbekDeveloper commented on 2. Xizmatlar/2.3 Orchestrations/2.3 Orchestraions.md
> +Shuni tushunish muhimki, orkestratsiya servislari faqat ibtidoiy yoki yuqori tartibli bo'lishi mumkin bo'lgan ko'p obektli operatsiyalarni birlashtirish kerak bo'lganda talab qilinadi. Ba'zi arxitekt
2-gapni ham chiroyliroq qiling

2023-04-09 11:08 UTC, dostonbek-andijonlik commented
Assalomu alaykum. Tushunarli

2023-04-24 12:30 UTC, ElbekDeveloper commented
Shutting down due to inactivity

2023-04-24 12:30 UTC, closed without merging